@VehicleSalesFIAP.Api_HostAddress = http://localhost:5008
@ManagerAccessToken = paste-vehicle-manager-access-token-here
@BuyerAccessToken = paste-buyer-access-token-here

GET {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/health
Accept: application/json

###

GET {{VehicleSalesFIAP.Api_HostAddress}}/health
Accept: text/plain

###

POST {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles
Content-Type: application/json
Authorization: Bearer {{ManagerAccessToken}}

{
  "brand": "Toyota",
  "model": "Corolla",
  "year": 2022,
  "color": "Silver",
  "price": 95000
}

###

@VehicleId = replace-with-created-vehicle-id

GET {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles/{{VehicleId}}
Accept: application/json

###

PUT {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles/{{VehicleId}}
Content-Type: application/json
Authorization: Bearer {{ManagerAccessToken}}

{
  "brand": "Toyota",
  "model": "Corolla XEi",
  "year": 2022,
  "color": "Black",
  "price": 99000
}

###

GET {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles/available
Accept: application/json

###

POST {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles/{{VehicleId}}/purchase
Authorization: Bearer {{BuyerAccessToken}}

###

GET {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles/sold
Accept: application/json
Authorization: Bearer {{ManagerAccessToken}}

###

DELETE {{VehicleSalesFIAP.Api_HostAddress}}/api/v1/vehicles/{{VehicleId}}
Authorization: Bearer {{ManagerAccessToken}}

###
